### ISSUE TITLE
can you add this link:

### ISSUE THREAD

**Issue by jovo** [jovo/cv#1]
https://www.usenix.org/system/files/conference/fast15/fast15-paper-zheng.pdf
it can replace the arxiv link to that manuscript.
thanks

**Comment by jovo** [comment]
is this done?

**Comment by ebridge2** [comment]
?Pushed

Eric Bridgeford
Johns Hopkins University
Dept. of Biomedical Engineering

**Comment by ebridge2** [comment]
still can't believe this came together so nicely; your CV looks awesome!

**Comment by jovo** [comment]
agreed!
and one day, i'll meet with my grant admin, and will get all my funding in
place, and then it will look even awesomer!

On Tue, Mar 10, 2015 at 2:37 AM, ebridge2 notifications@github.com wrote:

>  Closed #1 https://github.com/jovo/cv/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/1#event-249098878.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
