### ISSUE TITLE
add talks:

### ISSUE THREAD

**Issue by jovo** [jovo/cv#10]
1) Kavli Coffee Hour
"Challenges in Big Data Neuroscience"
at JHU
april 6

2) "Law of Large Graphs"
at DARPA GRAPHS PI Meeting
3/26

links to stuff will be in dropbox folder

**Comment by ebridge2** [comment]
![image](https://cloud.githubusercontent.com/assets/8883547/9392120/caf66594-4748-11e5-9779-81ca90a84446.png)
that's all that's in 2015 as of now... upload them pls

**Comment by jovo** [comment]
@ebridge2 you got the talks right? so you can add them to figshare and cv?

**Comment by ebridge2** [comment]
Yah they're all on dogs hare just have to link back

**Comment by jovo** [comment]
Dogs Hare = figs hare?

**Comment by ebridge2** [comment]
whoops; was from my phone. blame autocorrect for not having figshare as a
default entry in the dictionary :)

On Fri, Aug 21, 2015 at 1:07 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> Dogs Hare = figs hare?
>
