### ISSUE TITLE
recent articles aren't uploaded to research gate

### ISSUE THREAD

**Issue by jovo** [jovo/cv#16]
see here: https://www.researchgate.net/requests
(when logged in as me).

**Comment by ebridge2** [comment]
can you send me an email with your figshare/research gate username and passwords? I recently wiped my history on chrome, and with it your passwords went away as well :)

**Comment by ebridge2** [comment]
also your dropbox passwd

**Comment by jovo** [comment]
figshare: joshuav@jhu.edu / auo0r6hk
researchgate: jovo@stat.duke.edu / Asdf!234

you don't need my dropbox password.  do you want me to re-invite you to some folders?

**Comment by ebridge2** [comment]
nah forgot that folder was a shared one [😊]  have access I need

Eric Bridgeford
Johns Hopkins University
Dept. of Biomedical Engineering
