### ISSUE TITLE
12 L. Chen, J. Vogelstein, and C. Priebe. Robust Vertex Classification. PAMI, 1311.5954:27, 2013.

### ISSUE THREAD

**Issue by jovo** [jovo/cv#22]
was accepted, so move down to 'peer reviewed journal pubs'

**Comment by ebridge2** [comment]
do you have any other info for me? was it 2013? you had a previous issue for this that i commented for month, date and stuff like that

**Comment by jovo** [comment]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7159084&matchBoolean=true&pageNumber=2&searchWithin%5B%5D=%22Last+Name%22%3Avogelstein&newsearch=true
