### ISSUE TITLE
update figshare with all recent posters & slides

### ISSUE THREAD

**Issue by jovo** [jovo/cv#25]
@ebridge2 ask me if you don't know where the links are.

**Comment by ebridge2** [comment]
all im seeing in the 2015 folder is the OHBM stuff... where is the rest of it?

**Comment by ebridge2** [comment]
@jovo

**Comment by jovo** [comment]
maybe that's all there is for posters.
but 'talks' has a bunch of other stuff...

On Thu, Aug 20, 2015 at 11:02 PM, ebridge2 notifications@github.com wrote:

> @jovo https://github.com/jovo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/25#issuecomment-133261160.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ebridge2** [comment]
hmm i don't see talks in my dropbox menu... reinvite?

**Comment by jovo** [comment]
sent.

On Thu, Aug 20, 2015 at 11:14 PM, ebridge2 notifications@github.com wrote:

> hmm i don't see talks in my dropbox menu... reinvite?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/25#issuecomment-133263377.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ebridge2** [comment]
assuming you want all of these in your cv as well so ill link everything that's not there already...

**Comment by jovo** [comment]
cool, thanks.

On Thu, Aug 20, 2015 at 11:37 PM, ebridge2 notifications@github.com wrote:

> assuming you want all of these in your cv as well so ill link everything
> that's not there already...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/25#issuecomment-133268706.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
