### ISSUE TITLE
add PMID to all the articles that have one

### ISSUE THREAD

**Issue by jovo** [jovo/cv#27]
this might need modifying the bst file? i hope not though.
let me know if it does, and maybe we'll punt on it.

**Comment by ebridge2** [comment]
yep; to get the pmid into the items would require modifying the bst a bit. let me know if you want me to try it... might take a good bit of playing with to get right

**Comment by jovo** [comment]
ok, let's hold off on this one.

On Thu, Aug 20, 2015 at 11:01 PM, ebridge2 notifications@github.com wrote:

> yep; to get the pmid into the items would require modifying the bst a bit.
> let me know if you want me to try it... might take a bit of playing with to
> get right
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/27#issuecomment-133261014.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
