### ISSUE TITLE
update research gate

### ISSUE THREAD

**Issue by jovo** [jovo/cv#30]
a bunch of people seem to want full text articles or something.

**Comment by ebridge2** [comment]
finished all but 2... the 2 other requests cannot be fulfilled as I do not believe the files exist (somebody requested a full text for the CPAC, and somebody else requested a full text for the poster, are all brains wired equally? which already has its poster attached)

**Comment by ebridge2** [comment]
reopen if i the files exist and just aren't in your dropbox yet
