### ISSUE TITLE
update current funding

### ISSUE THREAD

**Issue by jovo** [jovo/cv#41]
- [ ] all "current" grants on the attached
- [ ] and this one:
  "Predoctoral Training Program in Computational Medicine"
  7-1-2015 - 6-230-2020

**Comment by mlee156** [comment]
I need more information like the DARPA/R0 code and the PI information

**Comment by jovo** [comment]
can you clarify and be specific?
which grant needs which exact info?
thanks, j

On Wed, Sep 23, 2015 at 7:08 PM, alee156 notifications@github.com wrote:

> I need more information like the DARPA/R0 code and the PI information
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/41#issuecomment-142756617.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
