### ISSUE TITLE
please add http://arxiv.org/abs/1509.03927#

### ISSUE THREAD

**Issue by jovo** [jovo/cv#42]

**Comment by mlee156** [comment]
This one and the Airan paper should be under peer reviewed right?

**Comment by jovo** [comment]
both are "under review"
thanks

On Wed, Sep 23, 2015 at 7:10 PM, alee156 notifications@github.com wrote:

> This one and the Airan paper should be under peer reviewed right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/42#issuecomment-142756903.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by mlee156** [comment]
For the Mouse and Man funding, the code is
 \cventry{9/14 -- 6/19}{Synaptomes of Mouse and Man}{NIH (TRA)}{R01 OD19123}{Smith (PI)}{}

For all the grants that are on the document you sent to me, I don't know where to find the "R01 OD19123" part. Also the "Smith (PI)" section is missing from the document as well.

**Comment by mlee156** [comment]
Most of the information for that is already up, but specifically for the SIMPLEX funding, Learning Causes Changes funding, Quantifying Individual Differences funding, and Collaborative Research funding.
