### ISSUE TITLE
posters?

### ISSUE THREAD

**Issue by jovo** [jovo/cv#43]
can you give me bib entries for all the posters we presented together?
i don't seem to have most of them (see cv for which ones i do have).

@willgray @gkiar @aksimhal 

@alee156 will collect them in put them in my cv for me.
thank you

**Comment by alexbaden** [comment]
I don't think I have presented a poster with you, yet.

Do you want a bib entry for the upcoming SfN poster?

Alex

**Comment by jovo** [comment]
@alexbaden yes please

**Comment by wrgr** [comment]
I'll dig. Other than sfn, I thought your list was complete - I found a
couple I had forgotten. Anything in particular you are pondering?

**Comment by jovo** [comment]
Anything in 2014

**Comment by alexbaden** [comment]
Not sure what the bib entry should be, but here's the poster info:

```
Web visualization of massive neuroscience datasets using the open connectome project
A. D. BADEN, K. A. LILLANEY, W. GRAY RONCAL, J. T. VOGELSTEIN, R. BURNS
Neuroscience 2015
```
