### ISSUE TITLE
i have 2 papers with koutra

### ISSUE THREAD

**Issue by jovo** [jovo/cv#49]
the one listed in peer review is a peer review,
the correct info is in an email that i'll forward.
the other one is the one that is already on the arxiv.
but it isn't listed.

@ebridge2 please help @alee156 fix this asap? lemme know if you guys have questions.

link to peer reviewed paper: 
http://web.eecs.umich.edu/~dkoutra/papers/DeltaCon_TKDD15.pdf

which also should go on arxiv.
thank you

**Comment by mlee156** [comment]
Did you send the email? I never got it. What's the name of the one that's already on the arxiv.

**Comment by mlee156** [comment]
DeltaCon: A Principled Massive-Graph Similarity Function is the one where the information is incorrect, 
and the DELTACON: Measuring Connectivity Differences in large networks is the one I need to include?

**Comment by mlee156** [comment]
I edited the information to what I think is correct but please let me know if I screwed something up

**Comment by jovo** [comment]
somewhat screwed up :)
we'll talk on friday?

**Comment by mlee156** [comment]
Damn...my bad.
I'll see you Friday.

Best,
Albert

**Comment by mlee156** [comment]
Hi Professor Vogelstein,

Just wondering if you're still free to meet at 4:30 today.

Best,
Albert

**Comment by jovo** [comment]
i'm free now. come?

On Fri, Oct 9, 2015 at 2:03 PM, alee156 notifications@github.com wrote:

> Hi Professor Vogelstein,
> 
> Just wondering if you're still free to meet at 4:30 today.
> 
> Best,
> Albert
> 
> On Thu, Oct 8, 2015 at 1:34 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > somewhat screwed up :)
> > we'll talk on friday?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/cv/issues/49#issuecomment-146425203.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/49#issuecomment-146949362.

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by mlee156** [comment]
I just finished my meeting, are you still free?

**Comment by jovo** [comment]
peer-reviewed journal #2: http://web.eecs.umich.edu/~dkoutra/papers/DeltaCon_TKDD15.pdf
- [ ] upload to arxiv
- [ ] update cv to correct title and arxiv link

**Comment by mlee156** [comment]
![screen shot 2015-10-18 at 3 19 18 am](https://cloud.githubusercontent.com/assets/14059912/10563054/e06c0fd8-7546-11e5-9a65-866ce754da7f.png)

**Comment by mlee156** [comment]
Do you have the tex file for this paper?

**Comment by jovo** [comment]
no, but you can upload a pdf, they just don't like it.

On Sun, Oct 18, 2015 at 2:18 AM, alee156 notifications@github.com wrote:

> Do you have the tex file for this paper?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/49#issuecomment-148986481.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by mlee156** [comment]
I know you can upload a pdf, but it insists that this particular file is not acceptable - there's no option to submit

**Comment by mlee156** [comment]
I need a smaller version of the source files to upload to arxiv

**Comment by jovo** [comment]
what do you mean?
source files are text and images.
you mean images are too large?
downsample them (in previous, for example).
make sense?

On Sun, Nov 29, 2015 at 2:56 PM, alee156 notifications@github.com wrote:

> I need a smaller version of the source files to upload to arxiv
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/49#issuecomment-160461289.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by mlee156** [comment]
How do you downsample images? Photoshop?
Also sorry if communication is a bit slow, I have the flu...

**Comment by jovo** [comment]
no worries.
google will tell you.
if you have a mac preview will do it
if not, i'm sure some online tool will do it for free.

On Sun, Nov 29, 2015 at 5:56 PM, alee156 notifications@github.com wrote:

> How do you downsample images? Photoshop?
> Also sorry if communication is a bit slow, I have the flu...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/49#issuecomment-160479313.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
@MrAE i think my koutra papers are still messed up, links are wrong or something.
links should go to doi for appropriate conference/journal.

**Comment by MrAE** [comment]
I'll get to these first thing in the morning.

**Comment by MrAE** [comment]
I think I fixed both Koutra papers.  @jovo, please check and close if they are correct.

**Comment by jovo** [comment]
closing this, i noted a minor issue in the other issue.
