### ISSUE TITLE
add talks

### ISSUE THREAD

**Issue by jovo** [jovo/cv#50]
1) DARPA SIMPLEX PI Meeting, September 2015
the two talks are in here:
https://www.dropbox.com/sh/ijoldply8ebg357/AAAVzlDVCovyNo8xC1HFMCMLa?dl=0

please post them to slideshare.

2) Kavli Special Symposium: Neuroscience in the 21st Century
link to talk?
http://www.kavlifoundation.org/special-symposium-neuroscience-21st-century
i start at 2:30:30

3) this one: 
http://casc.org/meetings/15oct/CASC%20Agenda%20Fall%202015.pdf

**Comment by mlee156** [comment]
I've never used Slideshare before, do I upload the files to LinkedIn through the general upload system, or do I have to upload it to a private group?

**Comment by mlee156** [comment]
Also it says that the SIMPLEX talks have been moved to a different location

**Comment by jovo** [comment]
eric knows all.

On Wed, Oct 7, 2015 at 1:57 PM, alee156 notifications@github.com wrote:

> I've never used Slideshare before, do I upload the files to LinkedIn
> through the general upload system, or do I have to upload it to a private
> group?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/50#issuecomment-146278382.

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by mlee156** [comment]
The SIMPLEX files still say they're missing

**Comment by mlee156** [comment]
I think they cut you off on the Kavli video, I can't find your speech since the video cuts at 2:30:30

**Comment by mlee156** [comment]
I wasn't too sure what to do with the Kavli or CASC talks since I couldn't find them online so I directly added the link to the link section. Please check out the changes I've made and tell me if I screwed up.

**Comment by mlee156** [comment]
Use figshare

**Comment by mlee156** [comment]
For CASC use figshare
