### ISSUE TITLE
Update CV

### ISSUE THREAD

**Issue by MrAE** [jovo/cv#56]
Issue generated from email on 20160316 18:48

**Comment by jovo** [comment]
whoa, so cool!
did you use zapier to set that up?
can i email issues and assign them to you directly?

On Wed, Mar 16, 2016 at 10:13 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Issue generated from email on 20160316 18:48
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/56

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
No, but apparently I comment like a bot. I didn't know zapier was a thing. I should look into that.

**Comment by jovo** [comment]
hilarious. yes, zapier is an awesome thing. i never set it up for emailing github issues, but one can, and the comments look like what you wrote.

**Comment by MrAE** [comment]
- [x] Robust Vertex Classification
- [x] A joint graph inference case study: the C. elegans chemical and electrical connectomes [links updated] 
- [x] Factors affecting characterization and localization of interindividual differences in functional connectivity using MRI
- [x] FlashMatrix: Parallel, Scalable Data Analysis with Generalized Matrix Operations using Commodity SSDs [SC16] -- **Need more info for this one**
