### ISSUE TITLE
cv updates

### ISSUE THREAD

**Issue by jovo** [jovo/cv#58]
### funding
- [x]  graphs ended, move to past
- [x]  BIG-DATA ended, move to past
### work experience
- [x]  Jan 16 - Present: Co-Founder & Partner, d8alab
### under review

the following have been accepted:
- [x] 1, 6, 7, 8
### invited talks
- [x]  NeuroData: Enabling Terascale Neuroscience for Everyone, State of the Brain Meeting, 2016 (link to ndintro).
### poster presentations
- [x]  same neurodata title, Janelia High-Resolution conference (it was a couple months ago, i don't remember the name)  @jovo Check this. 
#### reviewer
- [x]  Nature Communications
#### organizer
- [x] Global Brain Workshop http://brainx.io

**Comment by jovo** [comment]
@MrAE i am applying to this: http://www.alleninstitute.org/what-we-do/brain-science/about/advisors/next-generation-leaders/
my application is already late, unfortunately.
they have given me permission to submit it in a couple days
so, can we update my cv asap?

when i get home, we can prioritize stuff going forward.
thanks

**Comment by MrAE** [comment]
I'll get to this tonight and push what I get finished.

**Comment by jovo** [comment]
Thanx!

On Sunday, June 12, 2016, Jesse Leigh Patsolic notifications@github.com
wrote:

> I'll get to this tonight and push what I get finished.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/cv/issues/58#issuecomment-225463028, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjclFN77ltEH-P5LjOuBGMgO3e-fTpks5qLIExgaJpZM4It1IZ
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by MrAE** [comment]
@jovo, please close if satisfactory.
