### ISSUE TITLE
12 J. T. Vogelstein, J. M. Conroy, V. Lyzinski, L. J. Podrazik, S. G. Kratzer, E. T. Harley, D. E. Fishkind, R. J. Vogelstein, and C. E. Priebe. Fast Approximate Quadratic Programming for Large (Brain) Graph Matching. arXiv, 1112.5507, December 2011.

### ISSUE THREAD

**Issue by jovo** [jovo/cv#6]
is now accepted at PLoS One.
please update

**Comment by jovo** [comment]
here is link: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0121002

**Comment by ebridge2** [comment]
commenting that these are done and then ill check/close all of them at once after i visually make sure they all look fine after editing
