### ISSUE TITLE
Under Review: Missing papers

### ISSUE THREAD

**Issue by MrAE** [jovo/cv#60]
@MrAE - please change name of "Under Review Journal Pre-Prints" to just "Under Review"
- [X] put these there.
- [ ] see if anything else from here: http://arxiv.org/find/all/1/au:+Vogelstein_J/0/1/0/all/0/1 did not make it in to that section yet, and if so, please add.

**Comment by MrAE** [comment]
Regarding checkbox 2, I checked 1-9 from [here](http://arxiv.org/find/all/1/au:+Vogelstein_J/0/1/0/all/0/1) and added those that were missing. I'll have to take another run at 10+

**Comment by jovo** [comment]
thanks so much dude!

On Tue, Jun 14, 2016 at 10:09 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Regarding checkbox 2, I checked 1-9 from here
> http://arxiv.org/find/all/1/au:+Vogelstein_J/0/1/0/all/0/1 and added
> those that were missing. I'll have to take another run at 10+
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/cv/issues/60#issuecomment-225892767, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcoQ20mHUu-1vN3o3YXy-aGi9p0nBks5qLrYAgaJpZM4I1XAF
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
anything else?

**Comment by jovo** [comment]
assuming nothing else?

**Comment by MrAE** [comment]
The search page went over 10+ I only did 1-9 and never got to a second run.
