### ISSUE TITLE
a few more little issues (hopefully the last

### ISSUE THREAD

**Issue by jovo** [jovo/cv#61]
- [x] papers under "peer reviewed journal pubs" should never have 'arxiv' as the journal, we have a few of them.
- [x] "5 D. Koutra, J. T. Vogelstein, and C. Faloutsos. DeltaCon: A Principled Massive-Graph Similarity Function, chapter 17, pages 162–170. 2013." does not list the journal.

**Comment by MrAE** [comment]
@jovo Please comment with the journals to which these belong:
1.  K. S. Kutten, J. T. Vogelstein, N. Charon, L. Ye, K. Deisseroth, and M. I. Miller Deformably Registering and Annotating Whole CLARITY Brains to an Atlas via Masked LDDMM.
2. R. Airan et al "Stability and Localization of inter-individual differences in functional connectivity"

**Comment by jovo** [comment]
- [X] was in SPIE Europe (a conference, not journal)
- [X] Human Brain Mapping (a journal, not conference)
- [x] please add http://arxiv.org/abs/1412.4098 to under review 

On Thu, Jun 16, 2016 at 10:50 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @jovo https://github.com/jovo Please comment with the journals to which
> these belong:
> 1. K. S. Kutten, J. T. Vogelstein, N. Charon, L. Ye, K. Deisseroth, and M.
> I. Miller Deformably Registering and Annotating Whole CLARITY Brains to an
> Atlas via Masked LDDMM.
> 2. R. Airan et al "Stability and Localization of inter-individual
> differences in functional connectivity"
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/cv/issues/61#issuecomment-226508673, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcgU4h0AusWMWKDoFsv0yFJQirrJCks5qMWKtgaJpZM4I2-f9
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
