### ISSUE TITLE
Durante JASA Paper: 

### ISSUE THREAD

**Issue by MrAE** [jovo/cv#63]
@jovo The entry looks like this:

> D. Durante, D. B. Dunson, and J. T. Vogelstein. Nonparametric Bayes Modeling of Populations of Networks. JASA, 2014.
- [ ] Check if the year should be changed to 2016.

Comment if there are any other changes necessary.

**Comment by jovo** [comment]
yah, should be 2016, thanks.

**Comment by jovo** [comment]
close if cv is updated.
