### ISSUE TITLE
add this link to shuffled theory paper

### ISSUE THREAD

**Issue by jovo** [jovo/cv#8]
http://link.springer.com/article/10.1007/s00357-015-9170-6?sa_campaign=email/event/articleAuthor/onlineFirst

**Comment by jovo** [comment]
did you push the commits after making these changes?

On Thu, Apr 16, 2015 at 5:16 PM, ebridge2 notifications@github.com wrote:

>  Closed #8 https://github.com/jovo/cv/issues/8.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/8#event-283444288.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
Not yet. I'm not finished doing all of them and I was going to do a full check of the pdf before pushing. 

Sent from my HTC

----- Reply message -----

**Comment by jovo** [comment]
ok, lemme know when you push...

On Thu, Apr 16, 2015 at 9:03 PM, ebridge2 notifications@github.com wrote:

>  Not yet. I'm not finished doing all of them and I was going to do a full
> check of the pdf before pushing.
> 
> Sent from my HTC
> 
> ----- Reply message -----
> From: "joshua vogelstein" notifications@github.com
> To: "jovo/cv" cv@noreply.github.com
> Cc: "ebridge2" ebridge2@jhu.edu
> Subject: [cv] add this link to shuffled theory paper (#8)
> Date: Thu, Apr 16, 2015 8:09 PM
> 
> did you push the commits after making these changes?
> 
> On Thu, Apr 16, 2015 at 5:16 PM, ebridge2 notifications@github.com
> wrote:
> 
> > Closed #8 https://github.com/jovo/cv/issues/8.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/cv/issues/8#event-283444288.
> 
> ## 
> 
> the glass is all full: half water, half air.
> openconnecto.me, jovo.me, my calendar
> <
> https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jovo/cv/issues/8#issuecomment-93865764
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/8#issuecomment-93871543.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
Check it out; pushed the batch of changes that are closed and they all look pretty decent. Let me know if you want anything else in the new "Teaching" category (maybe a short one sentence description of the course might be nice?)

Eric Bridgeford
Johns Hopkins University
Dept. of Biomedical Engineering

**Comment by jovo** [comment]
looks better :)
some things to fix:

-- under review 2: needs arxiv info
-- "Fast Approximate Quadratic Programming for Large (Brain) Graph
Matching" is now accepted at PLoS One
-- "shuffled" paper needs updated dates.

otherwise, i think perfect for now?

On Thu, Apr 16, 2015 at 9:45 PM, ebridge2 notifications@github.com wrote:

>  Check it out; pushed the batch of changes that are closed and they all
> look pretty decent. Let me know if you want anything else in the new
> "Teaching" category (maybe a short one sentence description of the course
> might be nice?)
> 
> Eric Bridgeford
> Johns Hopkins University
> Dept. of Biomedical Engineering
> 
> ---
> 
> From: joshua vogelstein notifications@github.com
> Sent: Thursday, April 16, 2015 9:08 PM
> To: jovo/cv
> Cc: Eric Bridgeford
> Subject: Re: [cv] add this link to shuffled theory paper (#8)
> 
> ok, lemme know when you push...
> 
> On Thu, Apr 16, 2015 at 9:03 PM, ebridge2 notifications@github.com
> wrote:
> 
> > Not yet. I'm not finished doing all of them and I was going to do a full
> > check of the pdf before pushing.
> > 
> > Sent from my HTC
> > 
> > ----- Reply message -----
> > From: "joshua vogelstein" notifications@github.com
> > To: "jovo/cv" cv@noreply.github.com
> > Cc: "ebridge2" ebridge2@jhu.edu
> > Subject: [cv] add this link to shuffled theory paper (#8)
> > Date: Thu, Apr 16, 2015 8:09 PM
> > 
> > did you push the commits after making these changes?
> > 
> > On Thu, Apr 16, 2015 at 5:16 PM, ebridge2 notifications@github.com
> > wrote:
> > 
> > > Closed #8 https://github.com/jovo/cv/issues/8.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jovo/cv/issues/8#event-283444288.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, my calendar
> > <
> > 
> > https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jovo/cv/issues/8#issuecomment-93865764
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/cv/issues/8#issuecomment-93871543.
> 
> ## 
> 
> the glass is all full: half water, half air.
> openconnecto.me, jovo.me, my calendar
> <
> https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/jovo/cv/issues/8#issuecomment-93872062>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/cv/issues/8#issuecomment-93876317.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
